package com.yourspresently.pojos;

public enum Category {
	PERSONALISED, ELECTRONICS, FASHION, ACCESSORIES, HOME, LIVING, BOOKS, 
	TOYS, GAMES, BEAUTY, GROOMING, JEWELRY, WATCHES, HANDMADE_CRAFT, SPORTS, 
	FOOD, FLOWERS, GIFT_CARDS,GIFT_VOUCHERS, LUXURY, PREMIMUM 
}